SEC-963: Remove `mendersoftware` integration from the configuration
cfengine/cf-bottom pull request #97
Opened 2023-12-08 09:23 UTC by lluiscampos

For the dependabot PRs, now we have started to use the built-in functionality to assign reviewers, so the `cf-bottom` functionality is now redundant and, in some cases, contradictory.

We were not making use of `report_open_prs` feature, so remove the whole integration.

2023-12-08 14:00 UTC, olehermanse requested changes

2023-12-08 14:00 UTC, olehermanse commented on config.json
> -        "ping_reviewers_dependabot"
The pinging can be reviewed. The report we are using and cannot be removed.

2023-12-22 09:46 UTC, lluiscampos commented
> @lluiscampos this is not true, we are using this. Please see:

My apologies, I thought that because we had no set `reviewers` in the configuration it was in effect not working.

I reverted it now, just in time for Christmas :gift_heart:

2024-01-02 12:53 UTC, olehermanse approved these changes
I made another fix, `"orgs"` should not be removed. Looks good now.

2024-01-02 12:53 UTC, merged